author:
  publisher: Svengeance
  publisherUrl: 'https://sven.ai'
application:
  name: Husky App
  version: 0.1
  installDirectory: HuskyVariables.Folders.ProgramFiles + "/HuskyApp"
clientMachineRequirements:
  supportedOperatingSystems:
    - Windows
    - Linux
  freeSpaceMb: 128
  memoryMb: 1024
dependencies:
  - DotNet:
      Range: '>=5.0.0'
      FrameworkType: Runtime
      Kind: RuntimeOnly
jobs:
  show-splash:
    tags:
      - Install
    steps:
      show-unix-splash:
        platforms:
          - Linux
          - OSX
          - FreeBSD
        task: Scripting.ExecuteInlineScript
        with:
          script: |
            cls &&
            echo Welcome to Husky-App! &&
            read -n 1 -r -s -p $'Press any key to continue installation...\n'
      show-windows-splash:
        platforms:
          - Windows
        task: Scripting.ExecuteInlineScript
        with:
          script: |
            cls &&
            echo Welcome to Husky-App! &&
            pause
  extract-husky-app:
    steps:
      extract-files:
        task: Resources.ExtractBundledResource
        with:
          resources: '**/*'
          targetDirectory: '{Folders.ProgramFiles}/HuskyApp'
  create-launch-file:
    steps:
      create-launch-script:
        task: Scripting.CreateScriptFile
        with:
          directory: '{Folders.ProgramFiles}/HuskyApp'
          fileName: launch
          script: 'dotnet "{Folders.ProgramFiles}/HuskyApp/HuskyApp.dll"'
      create-shortcut:
        task: Utilities.CreateShortcut
        with:
          shortcutLocation: '{folders.Desktop}'
          shortcutName: HuskyApp
          target: '{create-launch-file.create-launch-script.createdFileName}'
